# Generated by Django 4.2.5 on 2023-12-11 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='home',
            new_name='myhome',
        ),
    ]
