# Generated by Django 4.2.5 on 2023-12-12 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_rename_home_myhome'),
    ]

    operations = [
        migrations.AddField(
            model_name='myhome',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
