# Generated by Django 4.2.5 on 2023-12-12 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_myhome_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myhome',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
